export const CATEGORIES_INIT = 'INIT_CATEGORIES';
export const CATEGORIES_GET_ALL = 'CATEGORIES_GET_ALL';
export const CATEGORIES_GET_PAGE = 'CATEGORIES_GET_PAGE';
export const CATEGORIES_GET_BY_ID = 'CATEGORIES_GET_BY_ID';
export const CATEGORIES_ADD = 'CATEGORIES_ADD';
export const CATEGORIES_REMOVE = 'CATEGORIES_REMOVE';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER = 'USER_REGISTER';
