export const TOPICS_GET_ALL = 'TOPICS_GET_ALL';
export const CATEGORIES_GET_ALL = 'CATEGORIES_GET_ALL';

export const NEW_CATEGORY_IS_PUBLISHED = 'NEW_CATEGORY_IS_PUBLISHED';
export const NEW_TOPIC_IS_PUBLISHED = 'NEW_TOPIC_IS_PUBLISHED';

export const USER_GET = 'USER_ADD';
export const USER_GET_ALL = 'USER_ADD_ALL';
